services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: bash -c "python mt/manage.py makemigrations && python mt/manage.py migrate && python mt/manage.py runserver 0.0.0.0:8000"
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
