From python:3.13.5-slim-bullseye
ENV PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y gcc libpq-dev
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app