# Generated by Django 5.2.4 on 2025-07-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['name'], name='drug_name_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['dosage_type'], name='drug_dosage_type_idx'),
        ),
    ]
