# Generated by Django 5.2.4 on 2025-07-15 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_tracker', '0002_alter_drug_options_drug_drug_name_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('reminder_time', models.CharField(choices=[('after_wake_up', 'After wake up'), ('before_breakfast', 'Before breakfast'), ('after_breakfast', 'After breakfast'), ('before_lunch', 'Before lunch'), ('after_lunch', 'After lunch'), ('before_dinner', 'Before dinner'), ('after_dinner', 'After dinner'), ('before_sleep', 'Before sleep')], default='after_wake_up', max_length=50)),
                ('number_of_doses', models.PositiveIntegerField(blank=True, help_text='Total number of doses', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='End date for the reminder', null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medical_tracker.drug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'reminder_time'],
                'unique_together': {('user', 'drug')},
            },
        ),
    ]
