# Generated by Django 5.2.4 on 2025-07-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_tracker', '0004_alter_medicationreminder_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationreminder',
            name='end_date',
        ),
    ]
