# Generated by Django 5.2.4 on 2025-07-16 01:34

import medical_tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_tracker', '0006_medicalfile_fileimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimage',
            name='image',
            field=models.ImageField(upload_to=medical_tracker.models.file_path),
        ),
    ]
