# Generated by Django 5.2.4 on 2025-07-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_tracker', '0007_alter_fileimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimage',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploading', max_length=20),
        ),
    ]
